name: Check markdown links (Lychee)

on:
  repository_dispatch:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * 1"  # Every Monday

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.3.2
        id: lychee
        with:
          args: "--accept 200,204,429 --verbose --no-progress content/"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: ${{ steps.lychee.outputs.exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: lychee
